/*
 * OpenVolley - Open Source Volleyball PWA
 * Copyright (C) 2025 OpenVolley Contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

import { jsPDF } from 'jspdf';
import type { Match } from '../db/database';

export function exportMatchToPDF(match: Match) {
  const doc = new jsPDF();
  
  // Title
  doc.setFontSize(20);
  doc.text('OpenVolley - Match Report', 105, 20, { align: 'center' });
  
  // Teams
  doc.setFontSize(16);
  doc.text(`${match.teamAName} vs ${match.teamBName}`, 105, 35, { align: 'center' });
  
  // Date
  doc.setFontSize(10);
  const matchDate = new Date(match.startTime).toLocaleString();
  doc.text(`Date: ${matchDate}`, 105, 45, { align: 'center' });
  
  // Sets header
  doc.setFontSize(14);
  doc.text('Sets', 20, 60);
  
  // Table header
  doc.setFontSize(10);
  let y = 70;
  doc.text('Set', 25, y);
  doc.text(match.teamAName, 60, y);
  doc.text(match.teamBName, 120, y);
  doc.text('Winner', 160, y);
  
  // Sets data
  y += 10;
  match.sets.forEach((set) => {
    doc.text(`${set.setNumber}${set.isTiebreak ? ' (TB)' : ''}`, 25, y);
    doc.text(`${set.teamAScore}`, 60, y);
    doc.text(`${set.teamBScore}`, 120, y);
    doc.text(set.winner ? `Team ${set.winner}` : '-', 160, y);
    y += 8;
  });
  
  // Final score
  const teamAWins = match.sets.filter(s => s.winner === 'A').length;
  const teamBWins = match.sets.filter(s => s.winner === 'B').length;
  
  y += 10;
  doc.setFontSize(14);
  doc.text(`Final Score: ${teamAWins} - ${teamBWins}`, 20, y);
  
  if (match.endTime) {
    const winner = teamAWins > teamBWins ? match.teamAName : match.teamBName;
    y += 10;
    doc.text(`Winner: ${winner}`, 20, y);
  }
  
  // Footer
  doc.setFontSize(8);
  doc.text('Generated by OpenVolley - GPL-3.0 Licensed', 105, 280, { align: 'center' });
  
  // Save
  const filename = `volleyball-match-${new Date(match.startTime).toISOString().split('T')[0]}.pdf`;
  doc.save(filename);
}
