-- Synthetic stand-in for the Supabase schema, for tests only.
--
-- The real pg_dump is not available yet. This mirrors the live-schema
-- inventory (column names and type families observed through PostgREST) and
-- the auth.users definition from the migration plan's 000_prelude.sql. Code
-- under test must not depend on anything here beyond what the inventory
-- guarantees; schema details are discovered from the catalog at runtime.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TYPE public.sport_type AS ENUM ('indoor', 'beach');

-- auth schema as created by 000_prelude.sql
CREATE SCHEMA IF NOT EXISTS auth;
CREATE TABLE auth.users (
  id uuid PRIMARY KEY,
  email text NOT NULL,
  encrypted_password text,
  email_confirmed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  last_sign_in_at timestamptz,
  raw_user_meta_data jsonb NOT NULL DEFAULT '{}',
  raw_app_meta_data jsonb NOT NULL DEFAULT '{}',
  failed_attempts int NOT NULL DEFAULT 0,
  locked_until timestamptz
);
CREATE UNIQUE INDEX users_email_lower ON auth.users (lower(email));

CREATE TABLE public.matches (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  external_id text,
  game_n int,
  game_pin text,
  status text,
  scheduled_at timestamptz,
  current_set int,
  final_score text,
  winner text,
  test boolean DEFAULT false,
  sport_type public.sport_type,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  connections jsonb, connection_pins jsonb, match_info jsonb, officials jsonb,
  home_team jsonb, away_team jsonb, players_home jsonb, players_away jsonb,
  bench_home jsonb, bench_away jsonb, coin_toss jsonb, results jsonb,
  signatures jsonb, approval jsonb, manual_changes jsonb, set_results jsonb,
  sanctions jsonb,
  CONSTRAINT matches_external_id_unique UNIQUE (external_id)
);

CREATE TABLE public.sets (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  external_id text UNIQUE,
  match_id uuid REFERENCES public.matches (id) ON DELETE CASCADE,
  index int,
  home_points int,
  away_points int,
  finished boolean,
  test boolean DEFAULT false,
  start_time timestamptz,
  end_time timestamptz,
  sport_type public.sport_type,
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE public.events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  external_id text UNIQUE,
  match_id uuid REFERENCES public.matches (id) ON DELETE CASCADE,
  set_index int,
  type text,
  payload json,
  seq numeric,
  ts timestamptz,
  test boolean DEFAULT false,
  created_at timestamptz DEFAULT now(),
  lineup_left json,
  lineup_right json,
  serve_team text,
  serve_player int,
  score_a int,
  score_b int,
  state_snapshot json,
  sport_type public.sport_type
);

CREATE TABLE public.match_live_state (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  match_id uuid UNIQUE,
  current_set int, sets_won_a int, sets_won_b int, points_a int, points_b int,
  team_a_name text, team_a_short text, team_a_color text,
  team_b_name text, team_b_short text, team_b_color text,
  side_a text, serving_team text, match_status text,
  timeouts_a int, timeouts_b int,
  lineup_a json, lineup_b json, subs_a json, subs_b json,
  sanctions_a json, sanctions_b json, last_event_data json, set_results json,
  last_event_type text, last_event_team text, last_event_ts timestamptz,
  timeout_active boolean, timeout_started_at timestamptz,
  set_interval_active boolean, set_interval_started_at timestamptz,
  scorer_attention_trigger text,
  game_n int, league text, gender text,
  sport_type public.sport_type,
  updated_at timestamptz DEFAULT now(),
  CONSTRAINT match_live_state_match_id_fkey_cascade
    FOREIGN KEY (match_id) REFERENCES public.matches (id) ON DELETE CASCADE
);

CREATE TABLE public.profiles (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE REFERENCES auth.users (id) ON DELETE CASCADE,
  first_name text,
  last_name text,
  country text DEFAULT 'CHE',
  dob date,
  roles text[] DEFAULT ARRAY['scorer'],
  sport_type public.sport_type,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE public.user_matches (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
  match_external_id text NOT NULL,
  role text NOT NULL,
  sport_type public.sport_type,
  created_at timestamptz DEFAULT now(),
  UNIQUE (user_id, match_external_id, role)
);

CREATE TABLE public.referee_database (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  first_name text,
  last_name text,
  country text,
  dob date,
  sport_type json,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE public.teams (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  external_id text UNIQUE,
  name text,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE public.svrz_games (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  game_number text,
  datetime text, date text, time text,
  team_home text, team_away text, league text, gender text,
  hall text, city text, hall_address text, hall_postal_code text,
  match_type text, match_level text, championship_type text, group_display text,
  linesman_1 text, linesman_2 text,
  match_format int,
  referee_1_first_name text, referee_1_last_name text,
  referee_2_first_name text, referee_2_last_name text,
  referee_1_dob date, referee_2_dob date,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE public.beach_competition_matches (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  external_id text UNIQUE,
  game_n int,
  competition_name text,
  match_info json,
  officials json,
  scheduled_at timestamptz,
  status text,
  sport_type text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);
