-- Synthetic schema for the pgQuery / matchRestore tests.
-- It mirrors the live Supabase schema as far as the 2026-10 inventory could
-- observe it (column names and type families). It is NOT the real dump:
-- replace or extend it once schema_public.sql from Phase 0 exists.
-- json vs jsonb is mixed on purpose so both paths are exercised.
-- Shared by the pgQuery, matchRestore, auth and server end-to-end tests.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TYPE public.sport_type AS ENUM ('indoor', 'beach');

-- auth schema as created by the plan's 000_prelude.sql
CREATE SCHEMA IF NOT EXISTS auth;
CREATE TABLE auth.users (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  email text NOT NULL,
  encrypted_password text,             -- bcrypt ($2a$10$...)
  email_confirmed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  last_sign_in_at timestamptz,
  raw_user_meta_data jsonb NOT NULL DEFAULT '{}',
  raw_app_meta_data jsonb NOT NULL DEFAULT '{}',
  failed_attempts int NOT NULL DEFAULT 0,
  locked_until timestamptz
);
CREATE UNIQUE INDEX users_email_lower ON auth.users (lower(email));

CREATE TABLE public.matches (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  external_id text CONSTRAINT matches_external_id_unique UNIQUE,
  game_n int,
  game_pin text,
  status text,
  scheduled_at timestamptz,
  current_set int,
  final_score text,
  winner text,
  test boolean DEFAULT false,
  sport_type public.sport_type DEFAULT 'indoor',
  connections json,
  connection_pins jsonb,
  match_info json,
  officials json,
  home_team json,
  away_team json,
  players_home json,
  players_away json,
  bench_home json,
  bench_away json,
  coin_toss json,
  results json,
  signatures json,
  approval json,
  manual_changes json,
  set_results jsonb,
  sanctions json,
  -- beach rows (sport_type 'beach'): teams are team1 / team2
  team1_data jsonb DEFAULT '{}'::jsonb,
  team2_data jsonb DEFAULT '{}'::jsonb,
  players_team1 jsonb DEFAULT '[]'::jsonb,
  players_team2 jsonb DEFAULT '[]'::jsonb,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE public.sets (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  external_id text UNIQUE,
  match_id uuid REFERENCES public.matches(id) ON DELETE CASCADE,
  index int,
  home_points int DEFAULT 0,
  away_points int DEFAULT 0,
  finished boolean DEFAULT false,
  test boolean DEFAULT false,
  start_time timestamptz,
  end_time timestamptz,
  sport_type public.sport_type,
  team1_points integer DEFAULT 0,
  team2_points integer DEFAULT 0,
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE public.events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  external_id text UNIQUE,
  match_id uuid REFERENCES public.matches(id) ON DELETE CASCADE,
  set_index int,
  type text,
  payload json,
  seq numeric,
  ts timestamptz,
  test boolean DEFAULT false,
  created_at timestamptz DEFAULT now(),
  lineup_left json,
  lineup_right json,
  serve_team text,
  serve_player int,
  score_a int,
  score_b int,
  state_snapshot json,
  sport_type public.sport_type
);

CREATE TABLE public.match_live_state (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  match_id uuid UNIQUE CONSTRAINT match_live_state_match_id_fkey_cascade REFERENCES public.matches(id) ON DELETE CASCADE,
  current_set int,
  sets_won_a int,
  sets_won_b int,
  points_a int,
  points_b int,
  team_a_name text, team_a_short text, team_a_color text,
  team_b_name text, team_b_short text, team_b_color text,
  side_a text,
  serving_team text,
  match_status text,
  timeouts_a int,
  timeouts_b int,
  lineup_a json, lineup_b json, subs_a json, subs_b json,
  sanctions_a json, sanctions_b json, last_event_data json, set_results json,
  last_event_type text, last_event_team text, last_event_ts timestamptz,
  timeout_active boolean, timeout_started_at timestamptz,
  set_interval_active boolean, set_interval_started_at timestamptz,
  scorer_attention_trigger text,
  best_of int,
  game_n int,
  league text,
  gender text,
  sport_type public.sport_type,
  -- beach
  challenges_used_a smallint DEFAULT 0 NOT NULL,
  challenges_used_b smallint DEFAULT 0 NOT NULL,
  server_number smallint DEFAULT 0 NOT NULL,
  tto_active boolean DEFAULT false,      -- db/008_live_state_tto.sql
  tto_started_at timestamptz,
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE public.profiles (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
  first_name text,
  last_name text,
  country text DEFAULT 'CHE',
  dob date,
  roles text[] DEFAULT ARRAY['scorer'],
  sport_type public.sport_type,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE public.user_matches (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  match_external_id text NOT NULL,
  role text NOT NULL,
  sport_type public.sport_type,
  created_at timestamptz DEFAULT now(),
  UNIQUE (user_id, match_external_id, role)
);

CREATE TABLE public.referee_database (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  first_name text,
  last_name text,
  country text,
  dob date,
  sport_type json,                      -- a JSON array, queried with contains
  created_at timestamptz DEFAULT now()
);

CREATE TABLE public.svrz_games (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  game_number text,
  datetime text, date text, time text,
  team_home text, team_away text, league text, gender text,
  hall text, city text, hall_address text, hall_postal_code text,
  match_type text, match_level text, championship_type text, group_display text,
  linesman_1 text, linesman_2 text,
  match_format int,
  referee_1_first_name text, referee_1_last_name text,
  referee_2_first_name text, referee_2_last_name text,
  referee_1_dob date, referee_2_dob date,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE public.beach_competition_matches (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  external_id text UNIQUE,
  game_n int,
  competition_name text,
  match_info json,
  officials json,
  scheduled_at timestamptz,
  status text,
  sport_type text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Present in the database but NOT on the allowlist.
CREATE TABLE public.internal_notes (
  id serial PRIMARY KEY,
  note text
);
INSERT INTO public.internal_notes (note) VALUES ('do not leak');
