// GENERATED by escoresheet/frontend/scripts/make-sign-core.mjs from
// escoresheet/frontend/public/sign/{index.html,sign.js,sign.css}. Do not edit: change the source, rerun.
//
// The phone page of Sign on phone, served by the cloud backend at /sign (the
// LAN relays serve the same files from their dist/). Same-origin with
// /api/sign/*, so it needs no CORS entry.
export const SIGN_PAGE_FILES = Object.freeze({
  'index.html': { type: 'text/html; charset=utf-8', body: "<!doctype html><meta charset=\"utf-8\"><title>OpenVolley</title><p>Phone signing is not built yet.</p>\n" },
  'sign.js': { type: 'text/javascript; charset=utf-8', body: "" },
  'sign.css': { type: 'text/css; charset=utf-8', body: "" }
})

/** The file of a /sign* path (/sign, /sign/, /sign/index.html, /sign/sign.js, /sign/sign.css), or null. */
export function signPageFile(pathname) {
  if (pathname === '/sign' || pathname === '/sign/' || pathname === '/sign/index.html') return SIGN_PAGE_FILES['index.html']
  if (pathname === '/sign/sign.js') return SIGN_PAGE_FILES['sign.js']
  if (pathname === '/sign/sign.css') return SIGN_PAGE_FILES['sign.css']
  return null
}
