create extension if not exists pgcrypto;

create table if not exists teams (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  created_at timestamptz default now()
);

alter table teams
  add column if not exists external_id text,
  add column if not exists color text,
  add column if not exists test boolean default false,
  add column if not exists updated_at timestamptz default now();

create unique index if not exists teams_external_id_idx on teams(external_id);

create table if not exists players (
  id uuid primary key default gen_random_uuid(),
  team_id uuid references teams(id) on delete cascade,
  number int not null,
  name text not null,
  role text,
  created_at timestamptz default now()
);

alter table players
  add column if not exists external_id text,
  add column if not exists first_name text,
  add column if not exists last_name text,
  add column if not exists dob text,
  add column if not exists libero text,
  add column if not exists is_captain boolean default false,
  add column if not exists test boolean default false,
  add column if not exists updated_at timestamptz default now();

create unique index if not exists players_external_id_idx on players(external_id);
create index if not exists players_team_id_idx on players(team_id);

create table if not exists matches (
  id uuid primary key default gen_random_uuid(),
  home_team uuid references teams(id),
  away_team uuid references teams(id),
  scheduled_at timestamptz,
  status text default 'scheduled',
  created_at timestamptz default now()
);

alter table matches
  add column if not exists external_id text,
  add column if not exists home_team_id uuid references teams(id) on delete set null,
  add column if not exists away_team_id uuid references teams(id) on delete set null,
  add column if not exists hall text,
  add column if not exists city text,
  add column if not exists league text,
  add column if not exists bench_home jsonb,
  add column if not exists bench_away jsonb,
  add column if not exists officials jsonb,
  add column if not exists test boolean default false,
  add column if not exists updated_at timestamptz default now();

create unique index if not exists matches_external_id_idx on matches(external_id);
create index if not exists matches_scheduled_at_idx on matches(scheduled_at);

create table if not exists sets (
  id uuid primary key default gen_random_uuid(),
  match_id uuid references matches(id) on delete cascade,
  index int not null,
  home_points int default 0,
  away_points int default 0,
  finished boolean default false
);

alter table sets
  add column if not exists external_id text,
  add column if not exists test boolean default false,
  add column if not exists start_time timestamptz,
  add column if not exists end_time timestamptz,
  add column if not exists updated_at timestamptz default now();

create unique index if not exists sets_external_id_idx on sets(external_id);
create index if not exists sets_match_id_idx on sets(match_id);

create table if not exists events (
  id bigint generated by default as identity primary key,
  match_id uuid references matches(id) on delete cascade,
  set_index int not null,
  ts timestamptz default now(),
  type text not null,
  payload jsonb not null
);

alter table events
  add column if not exists test boolean default false,
  add column if not exists created_at timestamptz default now();

create index if not exists events_match_id_idx on events(match_id);
create index if not exists events_ts_idx on events(ts);

create table if not exists referees (
  id uuid primary key default gen_random_uuid(),
  first_name text not null,
  last_name text not null,
  created_at timestamptz default now()
);

alter table referees
  add column if not exists external_id text,
  add column if not exists seed_key text,
  add column if not exists country text,
  add column if not exists dob date,
  add column if not exists test boolean default false,
  add column if not exists updated_at timestamptz default now();

create unique index if not exists referees_seed_key_idx on referees(seed_key);

create table if not exists scorers (
  id uuid primary key default gen_random_uuid(),
  first_name text not null,
  last_name text not null,
  created_at timestamptz default now()
);

alter table scorers
  add column if not exists external_id text,
  add column if not exists seed_key text,
  add column if not exists country text,
  add column if not exists dob date,
  add column if not exists test boolean default false,
  add column if not exists updated_at timestamptz default now();

create unique index if not exists scorers_seed_key_idx on scorers(seed_key);

alter table teams enable row level security;
alter table players enable row level security;
alter table matches enable row level security;
alter table sets enable row level security;
alter table events enable row level security;
alter table referees enable row level security;
alter table scorers enable row level security;

drop policy if exists public_read_teams on teams;
drop policy if exists public_read_players on players;
drop policy if exists public_read_matches on matches;
drop policy if exists public_read_sets on sets;
drop policy if exists public_read_events on events;
drop policy if exists public_read_referees on referees;
drop policy if exists public_read_scorers on scorers;
drop policy if exists scorer_insert_events on events;

create policy public_read_teams    on teams    for select using (true);
create policy public_read_players  on players  for select using (true);
create policy public_read_matches  on matches  for select using (true);
create policy public_read_sets     on sets     for select using (true);
create policy public_read_events   on events   for select using (true);
create policy public_read_referees on referees for select using (true);
create policy public_read_scorers  on scorers  for select using (true);

create policy scorer_insert_events on events for insert with check (auth.role() = 'authenticated');

