create extension if not exists pgcrypto;

create table if not exists teams (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  created_at timestamptz default now()
);

create table if not exists players (
  id uuid primary key default gen_random_uuid(),
  team_id uuid references teams(id) on delete cascade,
  number int not null,
  name text not null,
  role text,
  created_at timestamptz default now()
);

create table if not exists matches (
  id uuid primary key default gen_random_uuid(),
  home_team uuid references teams(id),
  away_team uuid references teams(id),
  scheduled_at timestamptz,
  status text default 'scheduled',
  created_at timestamptz default now()
);

create table if not exists sets (
  id uuid primary key default gen_random_uuid(),
  match_id uuid references matches(id) on delete cascade,
  index int not null,
  home_points int default 0,
  away_points int default 0,
  finished boolean default false
);

create table if not exists events (
  id bigint generated by default as identity primary key,
  match_id uuid references matches(id) on delete cascade,
  set_index int not null,
  ts timestamptz default now(),
  type text not null,
  payload jsonb not null
);

alter table teams enable row level security;
alter table players enable row level security;
alter table matches enable row level security;
alter table sets enable row level security;
alter table events enable row level security;

-- Public read
create policy if not exists public_read_teams   on teams   for select using (true);
create policy if not exists public_read_players on players for select using (true);
create policy if not exists public_read_matches on matches for select using (true);
create policy if not exists public_read_sets    on sets    for select using (true);
create policy if not exists public_read_events  on events  for select using (true);

-- Authenticated writes (extend as needed)
create policy if not exists scorer_insert_events on events for insert with check (auth.role() = 'authenticated');


